version: "3.5"

services:
  app:
    build: .
    container_name: directshare
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:$PORT

networks:
  default:
    external: true
    name: itskdhere
